version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ccs
      MYSQL_ROOT_PASSWORD: q1w2e3r4
    ports:
      - 33069:3306
    volumes:
      - ccs-db:/var/lib/mysql

volumes:
   ccs-db: